apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: kuliaev-diplom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/mkuliaev/my-nginx-app:v0.4.4
        ports:
        - containerPort: 80
