apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuliaev-diplom.ru
  namespace: kuliaev-diplom
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: kuliaev-diplom-nginx
          image:  mkuliaev/my-nginx-app:latest
          resources:
             requests:
                cpu: "1"
                memory: "200Mi"
             limits:
                cpu: "2"
                memory: "500Mi"             
          ports:
            - containerPort: 80

      nodeSelector:
        app: web-app

