name: Build & Deploy

on:
  push:
    branches: [main]
    tags:    ['v*.*.*']

env:
  REGISTRY: docker.io
  IMAGE_NAME: mkuliaev/my-nginx-app
  K8S_NAMESPACE: default
  DEPLOYMENT_NAME: kuliaev-diplom.ru
  CONTAINER_NAME: kuliaev-diplom-nginx
  K8S_API: https://158.160.156.81:6443     # 👈 опционально

jobs:
# ---------- Build ----------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          push: true

# ---------- Deploy ----------
  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check connectivity
        run: |
          echo "Testing API reachability..."
          if ! timeout 3 bash -c "</dev/tcp/158.160.156.81/6443"; then
            echo "::error::API server unreachable"; exit 1
          fi

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Rollout
        run: |
          kubectl version --short
          kubectl -n ${{ env.K8S_NAMESPACE }} set image \
            deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.CONTAINER_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          kubectl -n ${{ env.K8S_NAMESPACE }} rollout status deployment/${{ env.DEPLOYMENT_NAME }}
